* Compilation of quick HOW-TOs for Spacemacs

** Table of Contents                                                 :TOC@4:
 - [[#compilation-of-quick-how-tos-for-spacemacs][Compilation of quick HOW-TOs for Spacemacs]]
     - [[#disable-a-package-completely][Disable a package completely]]
     - [[#disable-a-package-only-for-a-specific-major-mode][Disable a package only for a specific major-mode]]
     - [[#disable-company-for-a-specific-major-mode][Disable company for a specific major-mode]]
     - [[#change-special-buffer-rules][Change special buffer rules]]
     - [[#enable-navigation-by-visual-lines][Enable navigation by visual lines]]

** Disable a package completely
当有些包是你不想要的，你想卸载它，你可以通过文件 =~/.spacemacs=中变量 
=dotspacemacs-excluded-packages= 进行控制（如果有些已安装的layers需要这个包，
也会被卸载）：

#+begin_src emacs-lisp
  (setq-default dotspacemacs-excluded-packages '(package1 package2 ...))
#+end_src

** Disable a package only for a specific major-mode
你也可以通过=remove-hook=hook在特定mode下禁用特定的包。比如，你想在=python buffers
下禁用=flycheck=，你可以在=~/.spacemacs=文件中=dotspacemacs/config=函数中进行如下设置：

#+begin_src emacs-lisp
    (remove-hook 'python-mode-hook 'flycheck-mode)
#+end_src

*Hint* to know the name of the major-mode of the current buffer press:
~SPC h d v major-mode RET~

** Disable company for a specific major-mode
当你启用了=auto-company=，要想在特定的mode下禁用=company=，可能不太方便。
=Spacemacs=提供了一种简单的方法：就是在=~/.spacemacs=文件中，在函数=dotspacemacs/config=
中使用=spacemacs|disable-company=方法。比如，下面这段代码就是在=python-mode=时禁用=company=：

#+begin_src emacs-lisp
    (spacemacs|disable-company python-mode)
#+end_src

** Change special buffer rules
当你需要将有写buffers标记问无用时，你可以使用以下方法：你可以修改在=dotspacemacs/config=
中修改=spacemacs-useless-buffers-regexp=变量的值。
同样，
当你需要将有写buffers标记问无用时，你可以使用以下方法：你可以修改在=dotspacemacs/config=
中修改=spacemacs-useful-buffers-regexp=变量的值。

例如：
#+begin_src emacs-lisp
    ;; Only mark helm buffers as useless
    (setq spacemacs-useless-buffers-regexp '("\\*helm\.\+\\*"))

    ;; Marking the *Messages* buffer as useful
    (push "\\*Messages\\*" spacemacs-useful-buffers-regexp)
#+end_src

** Enable navigation by visual lines
将如下代码放置在=~/.spacemacs=中的=dostpacemacs/config=函数中就可以使用visual lines
移动行。

#+begin_src emacs-lisp
    ;; Make evil-mode up/down operate in screen lines instead of logical lines
    (define-key evil-motion-state-map "j" 'evil-next-visual-line)
    (define-key evil-motion-state-map "k" 'evil-previous-visual-line)
    ;; Also in visual mode
    (define-key evil-visual-state-map "j" 'evil-next-visual-line)
    (define-key evil-visual-state-map "k" 'evil-previous-visual-line)
#+end_src
